version: "3.6"

services:
  frontend:
    build: .
    environment:
      REACT_APP_ENDPOINT: http://host.docker.internal:65080
    ports:
      - "61080:80"

networks:
  default:
    name: projectset
    external: true



